"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$nodejs\
$line_break\
$character"""

# ─────────────────────────────────────
# Prompt Character
# ─────────────────────────────────────

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

# ─────────────────────────────────────
# Directory
# ─────────────────────────────────────

[directory]
read_only = " ro"

# ─────────────────────────────────────
# Git
# ─────────────────────────────────────

[git_branch]
format = "[$branch]($style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'

[git_status]
format = '[$modified( $conflicted$untracked$staged$renamed$deleted)( \[$ahead_behind$stashed\])]($style)'
conflicted = "!"
deleted    = "✕"
diverged   = "⇕"
modified   = "*"
renamed    = "→"
staged     = "+"
stashed    = "≡"
untracked  = "?"

# ─────────────────────────────────────
# Command Duration
# ─────────────────────────────────────

[cmd_duration]
format = " [$duration]($style)"
style = "yellow"

# ─────────────────────────────────────
# Langs
# ─────────────────────────────────────

[nodejs]
format = " [$symbol$version]($style)"
symbol = "node "
